### Question 1 

Nous définissons un nouveau système de variables $(\xi, t)$ où $\xi = z \sqrt{\frac{Ra}{4t}}$

Par la règle de dérivation en chaine, nous avons:

$$\frac{\partial}{\partial z} = \frac{\partial \xi}{\partial z}\frac{\partial}{\partial \xi} + \frac{\partial t}{\partial z}\frac{\partial}{\partial t}$$

$$\text{Où} \frac{\partial t}{\partial z} = 0 \text{  et} \frac{\partial \xi}{\partial z} = \sqrt{\frac{Ra}{4t}}$$

On obtient donc 
$$\frac{\partial}{\partial z} = \sqrt{\frac{Ra}{4t}}\frac{\partial}{\partial \xi}$$

On peut également calculer

$$\frac{\partial ^2}{\partial z^2} = \frac{\partial}{\partial z}\left(\frac{\partial \xi}{\partial z}\frac{\partial}{\partial \xi}\right) = \frac{\partial ^2}{\partial z \partial \xi}\frac{\partial \xi}{\partial z} + \frac{\partial ^2\xi}{\partial z^2}\frac{\partial}{\partial \xi}$$

où 

$$\frac{\partial ^2\xi}{\partial z^2} = 0$$

et où 

$$\frac{\partial ^2}{\partial z \partial \xi} = \frac{\partial}{\partial \xi}\frac{\partial}{\partial z} = \frac{\partial}{\partial \xi}\frac{\partial}{\partial \xi}\frac{\partial \xi}{\partial z} = \frac{\partial \xi}{\partial z}\frac{\partial ^2}{\partial \xi ^2}$$

Ce qui nous donne 

$$ \frac{\partial ^2}{\partial z^2} = \left(\frac{\partial \xi}{\partial z}\right)^2 \frac{\partial ^2}{\partial \xi ^2} = \frac{Ra}{4t} \frac{\partial ^2}{\partial \xi ^2}$$

Par la règle de dérivation en chaine, nous calculons également la dérivée en le temps dans le nouveau système de coordonnées:

$$\frac{\partial}{\partial t} = \frac{\partial \xi}{\partial t}\frac{\partial}{\partial \xi} + \frac{\partial t}{\partial t}\frac{\partial}{\partial t}$$

Où 

$$\frac{\partial t}{\partial t} = 1$$

Et où 

$$\frac{\partial \xi}{\partial t} = z \sqrt{\frac{Ra}{4}} \frac{-1}{2}t^{-\frac{3}{2}} = -z\sqrt{\frac{Ra}{4t}}\frac{1}{2t}=-\frac{\xi}{2t}$$

Ce qui nous donne donc 

$$\frac{\partial}{\partial t} = -\frac{\xi}{2t}\frac{\partial}{\partial \xi} + \frac{\partial}{\partial t}$$

Pour le changement de coordonées.

Nous pouvons maintenant remplacer ces expressions. La première équation du système nous donne:

$$\left(\frac{\partial^2}{\partial z^2}-k^2\right)w = \left(\frac{Ra}{4t}\frac{\partial^2}{\partial \xi^2}-k^2\right)w = -k^2c$$

Pour la seconde équation, le membre de gauche devient:

$$\frac{\partial c}{\partial t}-\frac{1}{Ra}\left(\frac{\partial^2}{\partial z^2}-k^2\right)c = \left(-\frac{\xi}{2t}\frac{\partial}{\partial \xi} + \frac{\partial}{\partial t}\right)c - \frac{1}{Ra}\left(\frac{Ra}{4t}\frac{\partial^2}{\partial\xi^2}-k^2\right)c =\frac{\partial c}{\partial t}-\frac{1}{t}\left(\frac{1}{4}\frac{\partial^2}{\partial \xi^2}+\frac{\xi}{2}\frac{\partial}{\partial\xi}-\frac{k^2 t}{Ra}\right)c $$

Et nous avons directement, pour le membre de droite,

$$-\frac{\partial C_0}{\partial z}w =\frac{2}{\sqrt{\pi}}\sqrt{\frac{Ra}{4t}}e^{-\left(z\sqrt{\frac{Ra}{4t}}\right)^2}w=\sqrt{\frac{Ra}{\pi t}}e^{-\xi^2}w$$

### Question 2

In [1]:
from numpy import linalg
import numpy as np
from matplotlib import pyplot
%matplotlib inline

In [2]:
e=np.zeros(101)
for i in range (101):
    e[i]=0.05*i

print(e)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.   1.05 1.1  1.15 1.2  1.25 1.3  1.35
 1.4  1.45 1.5  1.55 1.6  1.65 1.7  1.75 1.8  1.85 1.9  1.95 2.   2.05
 2.1  2.15 2.2  2.25 2.3  2.35 2.4  2.45 2.5  2.55 2.6  2.65 2.7  2.75
 2.8  2.85 2.9  2.95 3.   3.05 3.1  3.15 3.2  3.25 3.3  3.35 3.4  3.45
 3.5  3.55 3.6  3.65 3.7  3.75 3.8  3.85 3.9  3.95 4.   4.05 4.1  4.15
 4.2  4.25 4.3  4.35 4.4  4.45 4.5  4.55 4.6  4.65 4.7  4.75 4.8  4.85
 4.9  4.95 5.  ]


In [4]:
#opérateur L:
L1=np.zeros((101,101))
for i in range(99):
    L1[i+1,i]=1
    L1[i+1,i+1]=-2
    L1[i+1,i+2]=1
L1

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1., -2.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1., -2., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., -2.,  1.,  0.],
       [ 0.,  0.,  0., ...,  1., -2.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [5]:
L2=np.zeros((101,101))
for i in range(99):
    L2[i+1,i+1]=k**2
    L2

In [6]:
L=np.dot(Ra/(4*t*(delta**2)),L1)-L2
print(L)

[[     0.              0.              0.         ...      0.
       0.              0.        ]
 [  8333.33333333 -16666.66676667   8333.33333333 ...      0.
       0.              0.        ]
 [     0.           8333.33333333 -16666.66676667 ...      0.
       0.              0.        ]
 ...
 [     0.              0.              0.         ... -16666.66676667
    8333.33333333      0.        ]
 [     0.              0.              0.         ...   8333.33333333
  -16666.66676667   8333.33333333]
 [     0.              0.              0.         ...      0.
       0.              0.        ]]


In [7]:
#opérateur M:
M1=np.zeros((101,101))
for i in range(99):
    M1[i+1,i]=-1
    M1[i+1,i+1]=2
    M1[i+1,i+2]=1
M2=np.zeros((101,101))
for i in range(99):
    M2[i+1,i]=-1*e[i+1]
    M2[i+1,i+1]=0
    M2[i+1,i+2]=1*e[i+1]
M3=np.zeros((101,101))
for i in range(99):
    M3[i+1,i+1]=1
print(M1)
print(M2)
print(M3)

M=np.dot(1/(4*t*(delta**2)),M1)+np.dot(1/(4*(delta)),M2)+np.dot((k**2)*t/(Ra),M3)
print(M)

[[ 0.  0.  0. ...  0.  0.  0.]
 [-1.  2.  1. ...  0.  0.  0.]
 [ 0. -1.  2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  2.  1.  0.]
 [ 0.  0.  0. ... -1.  2.  1.]
 [ 0.  0.  0. ...  0.  0.  0.]]
[[ 0.    0.    0.   ...  0.    0.    0.  ]
 [-0.05  0.    0.05 ...  0.    0.    0.  ]
 [ 0.   -0.1   0.   ...  0.    0.    0.  ]
 ...
 [ 0.    0.    0.   ...  0.    4.9   0.  ]
 [ 0.    0.    0.   ... -4.95  0.    4.95]
 [ 0.    0.    0.   ...  0.    0.    0.  ]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[  0.           0.           0.         ...   0.           0.
    0.        ]
 [-16.91666667  33.33333453  16.91666667 ...   0.           0.
    0.        ]
 [  0.         -17.16666667  33.33333453 ...   0.           0.
    0.        ]
 ...
 [  0.           0.           0.         ...  33.33333453  41.16666667
    0.        ]
 [  0.           0.           0.         ... -41.41666667  

### Question 3 ###

Nous avons donc

$$f(\xi) = e^{- \xi ^2} h(\xi)$$

Et on peut calculer

$$\frac{\partial f}{\partial \xi} = -2 \xi e^{- \xi ^2}h(\xi) + e^{- \xi ^2} h'(\xi)$$
$$\frac{\partial ^2 f}{\partial \xi ^2} = e^{- \xi ^2} h''(\xi) - 4 \xi e^{- \xi ^2} h'(\xi) + (4 \xi ^2 - 2) e^{- \xi ^2} h(\xi)$$

Et l'équation aux valeurs propres $Hf = \frac{1}{4} \frac{\partial^2 f}{\partial \xi^2}+\frac{\xi}{2}\frac{\partial f}{\partial\xi}=\alpha f $ devient donc:

$$Hf = \frac{1}{4} e^{- \xi ^2}(h''(\xi)-4\xi h'(\xi)+(4\xi^2- 2)h(\xi))+\frac{\xi}{2}e^{-\xi ^2}(h'(\xi) - 2\xi h(\xi)) = \alpha e^{-\xi ^2}h(\xi) $$

Qu'on simplifie pour obtenir

$$ h''(\xi) - 2\xi h'(\xi) = (4\alpha +2) h(\xi) $$

Cette dernière égalité est vérifiée par l'équation de Hermite pour $\lambda = -2\alpha -1$

$f$ est donc bien une fonction propre de $H$ de valeurs propres $\alpha = -\frac{\lambda + 1}{2}$

Nous utilisons les conditions aux bords pour obtenir les valeurs acceptables de $\alpha$

$f(\xi = \infty) = \lim_{\xi\to\infty} e^{-\xi^2}h(\xi) = 0$ quel que soit le degré du polynôme $h$

$f(\xi = 0) = \lim_{\xi\to 0} e^{-\xi^2}h(\xi) = h(0)$

Puisque les solutions de l'équation de Hermite sont les polynômes de Hermite des physiciens $H_\lambda(\xi)$, on a que le degré du polynôme doit être impair, pour que le terme de degré 0 soit nul.

On en déduit 
$$\lambda = 2n + 1, n \in \mathbb{N}$$

Ce qui nous permet d'obtenir 
$$\alpha = -n-1, n\in\mathbb{N}$$

Les valeurs acceptables de $\alpha$ sont donc les entiers strictement négatifs.

### Question 4

In [8]:
H=np.zeros((101,101))
H

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
for i in range(99):
    H[i+1,i]=1/(4*h**2)-e[i+1]/(4*h)
    H[i+1,i+1]=-1/(2*h**2)
    H[i+1,i+2]=1/(4*h**2)+e[i+1]/(4*h)
print(H)

[[   0.      0.      0.   ...    0.      0.      0.  ]
 [  99.75 -200.    100.25 ...    0.      0.      0.  ]
 [   0.     99.5  -200.   ...    0.      0.      0.  ]
 ...
 [   0.      0.      0.   ... -200.    124.5     0.  ]
 [   0.      0.      0.   ...   75.25 -200.    124.75]
 [   0.      0.      0.   ...    0.      0.      0.  ]]


In [10]:
D, V = np.linalg.eig(H)
print(D)

[-399.         -397.99999954 -396.99996223 -395.99884683 -394.98498415
 -393.90842709 -381.32800596 -383.69428059 -385.87635418 -387.8708373
 -378.78068155 -392.68964241 -376.0553717  -389.67389068 -373.15514682
 -370.08313917 -352.2635775  -356.14362884 -359.86928393 -348.23301005
 -363.43680116 -344.05594478 -339.73653659 -335.27907478 -366.84257631
 -325.96780137 -321.12321191 -316.15900532 -311.08009138 -305.89149143
 -300.59833382 -295.20584896 -289.71936446 -272.75053778 -266.94309198
 -261.06955877 -278.48616172 -255.13573747 -249.14748666 -243.11071841
 -391.28117598 -237.03139249 -230.91551051 -224.76911005 -218.59825869
 -212.40904809 -206.20758794 -200.         -193.79241206 -187.59095191
   -1.           -2.00000046   -3.00003777   -4.00115317   -5.01501585
   -6.09157291 -181.40174131   -7.31035759  -10.32610932  -12.1291627
  -14.12364582 -175.23088995  -16.30571941  -18.67199404  -21.21931845
 -150.85251334 -144.86426253 -138.93044123  -23.9446283  -133.05690801
  -99.40